### ISSUE TITLE
server: stress-test performance

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#194]
Stress-test performance of the REANA server and the whole REANA platform for the workshop use case of ~30 concurrent users creating workflows, uploading content, running workflows, checking status, and opening notebooks, all in parallel.

**Comment by diegodelemos** [comment]
- [x] Create a big cluster (already deployed 10 nodes cluster, production)
- [ ] Tune queue size and throttling mechanisms for incoming jobs to find peak performance (ease the task by making the parameters configurable

- [ ] Stress test the REST API via reana-client
- [ ] Stress test the REST API via scripts or [Locust](https://locust.io/)

<details><summary>More in depth details if needed ...</summary>
<p>

**Tune queue size and throttling mechanisms:*** As we advance in the stress tests, we will face that many workflows will be queued. The amount of running workflows until the next ones are queued is defined in [REANA-Commons configuration `K8S_MAXIMUM_CONCURRENT_JOBS`](https://github.com/reanahub/reana-commons/blob/0a57fb6f0d64a1392712d0567bf96e0f78d48bd5/reana_commons/config.py) and more complex conditions are defined in [REANA-Commons `tasks.py`](https://github.com/reanahub/reana-commons/blob/0a57fb6f0d64a1392712d0567bf96e0f78d48bd5/reana_commons/tasks.py). We should tune those, making the parameters configurable through environment variables so we can run tests and quickly change the setup helping in the search of the best configuration.

**Stress test REST API:** We could use a simple script to emulate this amount of users (for `reana-client`) or more advanced techniques as we have done in the past for CERN Open Data using [Locust](https://locust.io/), for more info see the [results](https://github.com/cernopendata/opendata.cern.ch/issues/2026) and the implementation [PR](https://github.com/cernopendata/opendata.cern.ch/pull/2214)) (REST API only actions).
</p>
</details>

**Comment by tiborsimko** [comment]
Tests done. Went up to ~40 parallel workflows and ~260 running pods.

Identified some bottlenecks (inefficient status query) that are dealt by separately. 

Identified some corner cases, the most important being:

```console
$ reana-client status -w roofit3
NAME      RUN_NUMBER   CREATED               STATUS   PROGRESS
roofit3   1            2020-02-06T10:37:04   failed   0/3   
$ reana-client logs -w roofit3
WORKFLOW ENGINE LOGS
ERROR:root:Job controller is not reachable.
NoneType: None
```

but these might have been caused by hot-upgrading of cluster components at the same time.

Otherwise everything was fine.
