### ISSUE TITLE
build error: invenio-rest>=1.1.0,<1.2.0

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#244]
After recent releases of Invenio packages, the REANA-Server's `master` branch does not build anymore:

```console
$  reana-dev docker-build -c r-server --no-cache
...
invenio-accounts 1.3.0 has requirement invenio-rest>=1.2.1, but you have invenio-rest 1.1.3.
The command '/bin/sh -c pip check' returned a non-zero code: 1
```

Let's check the changes in Invenio dependencies and either upgrade or pin older versions.

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-server/pull/245.
