### ISSUE TITLE
login: associate reana admin user to Invenio user

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-server#270]
**Current behavior**

We use the script [`create-admin-user.sh`](https://github.com/reanahub/reana/blob/master/scripts/create-admin-user.sh) to create an admin user [when deploying the cluster](https://github.com/reanahub/reana/blob/68e1d3b2cad4e55701d72f6015803f13372b3bce/reana/reana_dev/cluster.py#L283).

This user is only created [in the REANA DB](https://github.com/reanahub/reana-server/blob/master/reana_server/reana_admin.py#L79-L82) and not as Invenio user so it has a token to execute workflows but doesn't have credentials to sign in (as this is handled by Invenio-Accounts).

**Desired behavior**

- [x] Allow passing a password arg to `create-admin-user.sh`. Wrapping it with something like `reana-dev cluster-deploy --admin-email john.doe@example.org --admin-password mypass1234` which would do the necessary.
- [x] Create associated Invenio user when creating admin with [`reana-admin create-admin-user`](https://github.com/reanahub/reana-server/blob/master/reana_server/reana_admin.py#L60).
- [x] Once the above is implemented, the admin user should be able to sign in through the UI.

**Comment by tiborsimko** [comment]
(1) Note that currently `create-admin-user.sh` accepts two parameters:

- instance name
- email address

We should probably extend it to have a third parameter (password) passable... However note that the first two are optional, so we should probably hard-require them both and not assume anything anymore.

(2) Please amend `./helm/reana/templates/NOTES.txt` accordingly.
