### ISSUE TITLE
tokens: more informative request token email body

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#273]
When a user asks for token, we currently send the following email:

```
New user access token request:

id_: ....
email: john.doe@example.org
full_name: John Doe
username: johndoe
access_token: None
access_token_status: requested
```

It would be good to make it more user-friendly to REANA administrators, by doing:

(1) Add some greeting, perhaps:

```
Dear REANA administrator:
```

(2) Complete the message with actionable instructions, something like:

```
To accept the user token, please run:

$ kubectl ...

To reject the user token, please run:

$ kubectl ...
```

(3) Add some bottom line, perhaps simply:

```
Thanks,

<htttp://reana-qa.cern.ch>
```

**Comment by tiborsimko** [comment]
Let's also check how the letter looks like for non-SSO deployment scenarios.

**Comment by tiborsimko** [comment]
... and let's also prettify the message sent back to users after the token request is approved in a similar style.

**Comment by mvidalgarcia** [comment]
> Let's also check how the letter looks like for non-SSO deployment scenarios.

It's the same as there's a single endpoint `/token` to do this.

> ... and let's also prettify the message sent back to users after the token request is approved in a similar style.

This is how the message sent back looks like:

- Grant:
```
Dear marco@reana.io,

Your REANA access token has been granted, please find it on https://reana.cern.ch/profile

The REANA support team
```

- Revoke:

```
Dear marco@reana.io,

Your REANA access token has been revoked.

The REANA support team
```

How should we improve it?
