### ISSUE TITLE
rest: expose CPU and HDD quotas usage through REST API

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#279]
Two possible solutions:
1. Extend the existing [`/api/you` endpoint](https://reana-server.readthedocs.io/en/latest/_static/api.html#operation/get_you) to include quota usage (currently used to retrieve user information such as token status, email, username..)
2. Revive the [`/api/users` endpoint](https://reana-server.readthedocs.io/en/latest/_static/api.html#operation/get_user) which is currently not being used and it is admin only.

(1.) is MVP solution whereas (2.) would be a nice analogy with `/api/workflows` endpoint and could be used in admin interfaces. Eventually, both could coexist, one user-oriented, the other admin-oriented.

Note:
- HDD quota usage will come from https://github.com/reanahub/reana-commons/issues/207
- CPU quota usage TBD

**Comment by audrium** [comment]
Related PRs:
- reana-db: https://github.com/reanahub/reana-db/pull/84
- reana-server: https://github.com/reanahub/reana-server/pull/281
- reana-workflow-controller: https://github.com/reanahub/reana-workflow-controller/pull/334
