### ISSUE TITLE
api: prevent workflows from start if the user exceeds quota

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#282]
Prevent users from submitting new workflows when they have exceeded their quota.

The maximum quota can be:
- Centrally configured - MVP
  - For "institutional" users - @cern.ch users in our case (or configured list of institutional users e.g. [@cern.ch, @nyu.edu])
  - For "outside" users - in our concrete case non @cern.ch accounts, in general accounts that are not in the list of institutional users
  
    For example (note that naming is for illustration and it is not the best as we may need to use guests for real guests accounts, not logged in):
   ```console
    USERS_EMAILS = ["@cern.ch", "@nyu.edu"]
    USER_MAX_CPU_QUOTA = xyz
    GUEST_MAX_CPU_QUOTA = abc
    ```
- Set by user/group through admin interface (future)

Also, we have two moments in which a workflow can be prevented from running:
- When it is submitted ([REST API level](https://github.com/reanahub/reana-server/blob/2f389203c1d3ec5ace1fbf63eed3367a653eac20/reana_server/rest/workflows.py#L757)) (MVP)
- When [it is in the queue and it is going to be sent for execution to RWC](https://github.com/reanahub/reana-server/blob/2f389203c1d3ec5ace1fbf63eed3367a653eac20/reana_server/scheduler.py#L78)

**Comment by tiborsimko** [comment]
Using email may be tricky, because some users had primary address set to non-CERN, and it was causing some troubles during SSO detection in the past... However it could be a good first estimation which quotas to set after first registration/login. 

Since we don't have user groups yet, we could simply have quota limits defined for each user (in a new table) and use that; and the admins could be simply updating this table to set different quota limits for different user groups for now.

**Comment by tiborsimko** [comment]
... so for the task at hand, preventing starting new workflows, the r-server should check user quota upon workflow creation time, which could be done by simply comparing two numbers in a database, and refuse it to allow workflow creation/startingt/resuming if either of the quota resources (cpu, disk) are beyond respective quota resource limit.

**Comment by alintulu** [comment]
Tested `reana-client run` by creating two users and setting one limit on disk and one limit on cpu (using  `reana-admin quota-set`).

```
$ flask reana-admin quota-usage
ID                                     EMAIL              CPU-USED   CPU-LIMIT   DISK-USED   DISK-LIMIT   
eba4f120-4dce-4bcd-ac51-1367e92f1e19   test@reana.io      0          -           0           1         
263fbeea-7af7-4465-a218-4ad73831fcb2   johndoe@reana.io   0          20          0           - 

$ reana-client run -w serial --access-token HqTZ8e_HMUYdf0bMpC-GqQ[INFO] 
Creating a workflow...
serial.1
[INFO] Uploading files...
File /code/helloworld.py was successfully uploaded.
File /data/names.txt was successfully uploaded.
[INFO] Starting workflow...
serial.1 has been queued

$ reana-client run -w serial --access-token mEs9Vecu8RiDrE3OFA4ppQ
Creating a workflow...
serial.1
[INFO] Uploading files...
File /code/helloworld.py was successfully uploaded.
File /data/names.txt was successfully uploaded.
[INFO] Starting workflow...
serial.1 has been queued

$ flask reana-admin quota-usage
ID                                     EMAIL              CPU-USED   CPU-LIMIT   DISK-USED   DISK-LIMIT
eba4f120-4dce-4bcd-ac51-1367e92f1e19   test@reana.io      32768      -           9963        1         
263fbeea-7af7-4465-a218-4ad73831fcb2   johndoe@reana.io   32768      20          9789        - 

$ reana-client run -w serial --access-token HqTZ8e_HMUYdf0bMpC-GqQ[INFO] Creating a workflow...
Cannot create workflow serial: 
User quota exceeded.

$ reana-client run -w serial --access-token mEs9Vecu8RiDrE3OFA4ppQ[INFO] Creating a workflow...
Cannot create workflow serial: 
User quota exceeded.
```

Works as expected!
