### ISSUE TITLE
api: prevent sessions from start if the user exceeds quota

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#283]
With the outcome of https://github.com/reanahub/reana-server/issues/282 we should be able to add this prevention mechanism to the [session opening endpoint](https://github.com/reanahub/reana-server/blob/2f389203c1d3ec5ace1fbf63eed3367a653eac20/reana_server/rest/workflows.py#L1743).

**Comment by tiborsimko** [comment]
Interesting side problems: (a) how to measure the CPU of open, yet inactive notebooks (total time?) and (b) how to warn the user (inject headers into notebook? send email that this notebook will be closed soon?).

**Comment by alintulu** [comment]
Tested similarly as mentioned [here](https://github.com/reanahub/reana-server/issues/282#issuecomment-719592220).

```
$ reana-client open jupyter -w serial
Interactive session could not be opened: 
User quota exceeded.
```

Works as expected!
