### ISSUE TITLE
admin: allow admins to consult quota usage

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#284]
Enrich `reana-admin` to include a new command to show and inspect user quotas. The concrete data to be displayed will be determined by the outcome of https://github.com/reanahub/reana-db/issues/83.

We could show:
- Overall quota usage
- Per-user quota usage
- ...

**Comment by tiborsimko** [comment]
For MVP, a simple tabular output could do:

```
NAME       CPU-USED      CPU-LIMIT   DISK_USED     DISK_LIMIT 
johndoe         123          12345          10           1234
```

with green/yellow/red colouring based of 0-80, 80-95, 95-100 percentile or something.

The top users in red zone, and in orange zone, or top five users from green zone, could be added to daily system status messages.

P.S. For CPU, the numbers can be aggregated per month (or year?) and recycled; so we may need to show this information (from when, until when, kind of like phone 4G data usage).  For Disk, the numbers are always showing live aggregated status.
