### ISSUE TITLE
rest: combine usage and limits of different quota resources into dict

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-server#289]
We should combine quotas into some kind of dict (maybe something similar like [here](https://github.com/reanahub/reana-client/pull/425/files#diff-4f27f08c3f46f0b755c1d5ac1a1e2dcaR72)) and group the usage and limits of different quota resources before returning the response. 

_Originally posted by @audrium in https://github.com/reanahub/reana-server/pull/288#discussion_r498788299_

**Comment by mvidalgarcia** [comment]
Related https://github.com/reanahub/reana-server/pull/288#discussion_r498878024
