### ISSUE TITLE
auth: move to new CERN SSO

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-server#333]
From [`invenio-oauthclient 1.4.0`](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/CHANGES.rst#changes), new CERN OpenID contrib is supported, making it possible to upgrade.

When doing so take the following note from a previous task into account:

> Since SSO accounts also need confirmation, after signing up with one of those, we got redirected to the default Invenio-Accounts login page that doesn't exist (404), as it's a UI view (Invenio) that's not whitelisted in the Ingress controller.
> 
> In addition, as we're using a UI view to trigger the SSO auth (check [this awfullness](https://github.com/reanahub/reana-ui/pull/170/files#diff-37ec3004aa1b881eb0f0a93bf4c904a5295f638c81ecc26fbc553c70c92d244cR30)), we basically make full redirections, and reana-ui loses all context on what's happening. We can't know if the SSO sing in/up went successfully to display proper notifications from reana-ui.
> 
> This workflow is far from ideal. We should upgrade Invenio-Accounts to the latest version that supports REST apps, and revamp the whole workflow. As we also need to change to the new CERN SSO soon (supported in [latest Invenio-Accounts  version](https://github.com/inveniosoftware/invenio-oauthclient/blame/master/CHANGES.rst#L14)), that can be a good opportunity to tackle this problem.
> 
> Shall we open an issue with all this info?
> 
_Originally posted by @mvidalgarcia in https://github.com/reanahub/reana-server/issues/332#issuecomment-749516955_

This is an epic issue that can serve as an umbrella issue to many subtasks to be created when a sprint targets this topic.

**Comment by audrium** [comment]
Closing this one since the new SSO was implemented [here](https://github.com/reanahub/reana-server/issues/480) and it's already deployed to production
