### ISSUE TITLE
scheduler: start workflow that has best chances of immediately running

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#358]
Consider incoming workflow queue has two workflow runs W1 and W2 issued by the same user. 

Consider W1 spawns 20 n-tupling jobs each needing 8 GiB RAM, while W2 spawns 4 n-tupling jobs each needing 6 GiB RAM.

Consider the current cluster status is such that it has 36 GiB free memory for job slots.

In these conditions, it makes sense to launch W2 instead of W1, because W2 initial jobs may be immediately "running", whilst W1 jobs would be mostly in the "pending" state.

The goal of this issue is to walk through incoming workflow queue and decide upon which workflow to run based on the initial workflow job complexity.

This task depends on DAG analysis to discover initial workflow complexities, which will be ticketised separately as dependent issues.

Corner issues to consider:
- The above example expresses free cluster memory capacity as 36 GiB by one number, but in reality the free cluster memory capacity is defined by each node, e.g. it could be one node with more merory (1, 8GiB) or more nodes with fewer memory (4, 2GiB) slots. Hence, if incoming workflow W1 is (2, 2GiB) and W2 is (1, 3GiB), in the former case W2 should have priority, in the latter case W1 should have priority.
- Waiting times for workflows in the queue. E.g. W1 is so big and the cluster is so busy that W2 and even W9 and even W39 would be scheduled beforehand.  So the ultimate formula to pick the best workflow to start should be combination of how cluster is currently busy, what is currently possible, and how long a given workflow waits in the queue (or how many times it was skipped and "overtaken" by smaller workflows already).

Stems from #357.

**Comment by tiborsimko** [comment]
Depends on #359.

**Comment by audrium** [comment]
Since fetching all the queue messages from the consumer is a bit troublesome, another approach we could take is to use [RabbitMQ priority queues](https://www.rabbitmq.com/priority.html) - to set workflow priority depending on the complexity while publishing the message

**Comment by mvidalgarcia** [comment]
📪
