### ISSUE TITLE
dag: estimate initial workflow complexity for Serial workflows

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#359]
For Serial workflows, only one job runs at a time.  Hence the workflow complexity is easy, equal to 1.

However, the user may require the first job to have 8 GiB of RAM, or 2 GiB of RAM.  This may influence whether we can schedule the first job with reasonably high chances for it to be "running" rather than "pending".

The task needs to parse Serial workflow DAG and come up with a tuple  such as (1, 8 GiB) which means that the initial workflow stages will run 1 job only that will consume 8 GiB.

Note: if the desired computing backend is HTCondor or Slurm, the complexity could be virtually zero (!) because jobs will run elsewhere and are not really affected by the Kubernetes cluster CPU and RAM statuses.

**Comment by tiborsimko** [comment]
Note: another thing to consider is that users may want to start the workflow not from the initial stage, but from some other stage.  For example:

```console
$ reana-client restart -w myanalysis.42 -o FROM=fitdata
```

In this case, the DAG complexity should be calculated not for the initial stage, but for the "fitdata" stage.

Ditto for Yadage and CWL workflows when restarts are available there. 

This means that the function that estimate complexity should get a parameter which step to analyse, with "init" being the default.

**Comment by audrium** [comment]
Closing since it was implemented in https://github.com/reanahub/reana-server/pull/366
