### ISSUE TITLE
dag: estimate initial workflow complexity for CWL workflows

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#361]
This task is the same as #359 and #360 but for CWL workflows.

The challenges here are the same as for Yadage worklows in that scatter-gather may lead to running N jobs for the same step.

Otherwise it is the same, beware of HTCondor and Slurm backends, beware of desired memory, etc.

**Comment by audrium** [comment]
Closing since it was implemented in https://github.com/reanahub/reana-server/pull/366
