### ISSUE TITLE
scheduler: take into account pending workflows before starting new workflows

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-server#364]
Scheduler is [checking upper cluster limit only on running workflows](https://github.com/reanahub/reana-server/blob/master/reana_server/scheduler.py#L56). Since introducing `pending` workflows we need to amend this logic to also take into account pending workflows.

To reproduce this issue set `REANA_MAX_CONCURRENT_BATCH_WORKFLOWS` to 1.
Then quickly launch multiple `bsm-search` workflows. Since workflows spend a fraction of a second in `pending` state and scheduler only checks for `running` workflows, more than one can be started in one go:
```
NAME       RUN_NUMBER   CREATED               STARTED               ENDED   STATUS
workflow   6            2021-05-18T14:23:50   -                     -       queued
workflow   5            2021-05-18T14:23:49   -                     -       queued
workflow   4            2021-05-18T14:23:47   -                     -       queued
workflow   3            2021-05-18T14:23:44   2021-05-18T14:24:15   -       running
workflow   2            2021-05-18T14:23:42   2021-05-18T14:24:15   -       running
workflow   1            2021-05-18T14:23:40   2021-05-18T14:24:15   -       running
```

**Comment by mvidalgarcia** [comment]
My two cents about this. While playing with the new cluster status UI I've noticed that if I run workflows one by one, the `REANA_MAX_CONCURRENT_BATCH_WORKFLOWS`, is respected, however, when the queued workflows leave the queue, they change to `pending`, and after that all the pending workflow transition to `running`, ignoring the `REANA_MAX_CONCURRENT_BATCH_WORKFLOWS`.

To illustrate better I'll add some screenshots. I set `REANA_MAX_CONCURRENT_BATCH_WORKFLOWS = 2`:

1. I run 6 workflows one by one (I wait ~7 secs between runs so workflows can transition to `running`) 2 remain `running`, 4 `queued`

![image](https://user-images.githubusercontent.com/8863238/118795755-385d1c80-b89b-11eb-8af0-a29d6217cb17.png)

2. After some seconds, when the two workflows running finish, the 4 workflows queued transition to `pending` and after that, they transition to `running`, not respecting the limits whatsoever.

![image](https://user-images.githubusercontent.com/8863238/118796191-a86ba280-b89b-11eb-89b7-24ffa1be2379.png)
![image](https://user-images.githubusercontent.com/8863238/118796232-b4576480-b89b-11eb-97ff-60452f3fc6eb.png)
