### ISSUE TITLE
snakemake: DAG complexity estimation

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-server#392]
**Current behavior**

The [workflow complexity](https://github.com/reanahub/reana-db/blob/24afea938a4a4a4407d9c30e5ee91a98736acca5/reana_db/models.py#L443) is a value that we can calculate based on the amount of memory assigned to a particular workflow (or workflow step) and the _complexity_ of the initial workflow steps i.e. whether they can run in parallel or not.

This value is later used to assign priorities to workflows and thus being able to schedule simpler workflows before heavy ones even though the former were submitted later.

One can see how we [calculate the workflow complexity and obtain the workflow priority](https://github.com/reanahub/reana-server/blob/a029855d14d42ca187236bbfffcb4406ff27f003/reana_server/utils.py#L110-L111) before [submitting the workflow](https://github.com/reanahub/reana-server/blob/a029855d14d42ca187236bbfffcb4406ff27f003/reana_server/utils.py#L113-L119).

Currently, we support complexity estimation for Serial, Yadage and CWL. All the logic is present in this [module](https://github.com/reanahub/reana-server/blob/a029855d14d42ca187236bbfffcb4406ff27f003/reana_server/complexity.py) where there are classes for each of the workflow engines.

The complexity format is a list of 2-dimension tuples. E.g `[(2, 8Gi), (3, 4Gi)]`. This example represents a step that has 2 jobs that can run in parallel with 8Gi of memory assigned each, and a step of 3 jobs that can run in parallel with 4Gi of memory assigned each.

**Expected behavior**

This issue depends on the DAG parser being implemented in reanahub/reana-client#543 to have an internal representation of the Snakefile and be able to grab the different rules/steps a workflow has and whether they are scatter-gather or simple steps. This internal representation should be stored in [the `reana_yaml` dict](https://github.com/reanahub/reana-server/blob/a029855d14d42ca187236bbfffcb4406ff27f003/reana_server/complexity.py#L64) that the complexity estimator class receives as a parameter.

It also depends highly on creating a scatter-gather minimal example to be able to test it properly https://github.com/reanahub/reana/issues/530.

The goal of this issue is to implement a `SnakemakeComplexityEstimator` class with its associated [`parse_specification`](https://github.com/reanahub/reana-server/blob/a029855d14d42ca187236bbfffcb4406ff27f003/reana_server/complexity.py#L67-L69) method to parse the multiple rules and guess if they can run in parallel (scatter-gather) or not.

Despite the fact that this issue belongs to `reana-server`, it can be tested without the cluster running by importing the appropriate functions from a python shell.

```console
mkvirtualenv foo
pip install -e ../reana-client ../reana-server ipython
cd ../reana-demo-root6-roofit
ipython
```

```python
In [1]: from reana_client.utils import load_reana_spec

In [2]: from reana_server.complexity import estimate_complexity

In [3]: reana_yaml = load_reana_spec('./reana.yaml')
==> Verifying REANA specification file... ./reana.yaml
  -> SUCCESS: Valid REANA specification file.
==> Verifying REANA specification parameters... 
  -> SUCCESS: REANA specification parameters appear valid.
==> Verifying workflow parameters and commands... 
  -> SUCCESS: Workflow parameters and commands appear valid.
==> Verifying dangerous workflow operations... 
  -> SUCCESS: Workflow operations appear valid.

In [4]: from reana_server import complexity as reana_server_complexity

In [5]: reana_server_complexity.REANA_COMPLEXITY_JOBS_MEMORY_LIMIT = '4Gi'

In [6]: estimate_complexity('serial', reana_yaml)
Out[6]: [(1, 4294967296.0)]
```

As part of this issue it'd be nice to enrich [the complexity tests](https://github.com/reanahub/reana-server/blob/b5c84d9adec1d1bf5c09cea359b29ba62d3749b6/tests/test_complexity.py#L37) with a dummy Snakemake workflow.

**Comment by tiborsimko** [comment]
> pip install -e 

The test-outside-reana instructions are nice :+1: In the past we have been using `reana-client`, but this technique is nicer. One minor point: since the instructions are for only testing complexity, we can do simply `pip install` here, without using editable mode, in order to prevent mishaps.

You may want to put this up as a new dev wiki page "HowToTestWorkflowComplexity" on REANA GitHub wiki, so that it won't get lost in an old issue once this is closed... A good example for stuff to put into the nascent dev doc corner.

(Ditto for your k8s metrics installation recipe...)
