### ISSUE TITLE
rest: logging does not work correctly in production mode

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-server#417]
Currently on production mode installation there are some issues with `rest-api` logging:

1) It is only working for limited amount of endpoints. E.g. `/ping` is not being logged while `/api/you` logged as expected

2) There are lots of deprecation warnings in the logs like this:
```
<unknown>:1: DeprecationWarning: invalid escape sequence \[

2021-11-12 16:01:59,147 | py.warnings | uWSGIWorker2Core0 | WARNING | <unknown>:1: DeprecationWarning: invalid escape sequence \[
```
which are repeated for almost 1.5k lines after application starts. This could be due to outdated `invenio` dependencies. However it's not trivial to upgrade it because we have a conflicting `celery` dependency (from outdated `kombu` version which requires `celery<5.0.0` pinning).

3) Logging level set in reana-commons is not respected: https://github.com/reanahub/reana-server/issues/298

4) It seems that `factory.py` and `create_app()` are only being used in `reana-admin` and `scheduler` (defined [here](https://github.com/reanahub/reana-server/blob/master/setup.py#L103)). Needs a deeper investigation, but if that's the case there is no point in registering the blueprints there. Looks like [invenio-base](https://github.com/reanahub/reana-server/blob/master/setup.py#L107) is taking care for [starting up](https://github.com/reanahub/reana/blob/master/helm/reana/templates/reana-server.yaml#L42) the application. To reproduce try to:
    - comment/remove `factory.py` and `app.py`
    - `reana-dev docker-build -c . -b DEBUG=1`
    - `reana-dev kind-load-docker-image -c .`
    - kill the old pod and inspect the new one - works as expected
    - it does not work while redeploying the cluster because it can't start `flask reana-admin create-admin-user `

**Comment by mvidalgarcia** [comment]
After some research, I've discovered that [we're only printing 4xx and 5xx logs](https://github.com/reanahub/reana/blob/973b00908aa8c98f60f1a0ce54a764ddccc3dce0/helm/reana/templates/uwsgi-config.yaml#L27-L30) when using uwsgi. IIRC this was our decision, perhaps to avoid too much output and thus be able to detect errors easier. Should we keep it like this? @tiborsimko

**Comment by tiborsimko** [comment]
Good catch! I think printing everything is a better default, and if that is really too verbose, let's allow admins to change it easily. 
 This calls for making the behaviour configurable via Helm values...
