### ISSUE TITLE
Regex in _validate_email is very picky.

### ISSUE THREAD

**Issue by Debilski** [reanahub/reana-server#422]
Email addresses with a dash fail with `ERROR: Invalid email format`, which is very confusing when running the create-admin-user script.

https://github.com/reanahub/reana-server/blob/4c986b2847f546ee3eaac3a1d752dd77a2ff4ed6/reana_server/utils.py#L435-L439

**Comment by VMois** [comment]
In addition, I can see that emails with two dots are not working either, e.g `john.doe.poe@example.org`.

**Comment by VMois** [comment]
Another finding, emails that may come from educational institutions (and similarly formatted) are not supported either, e.g `joe.doe@edu.uni.ch` is not working.

**Comment by audrium** [comment]
Thanks @Debilski for spotting this issue! It's now fixed and will be included in the upcoming REANA 0.8.0 stable release which we are planning to release next week
