### ISSUE TITLE
epic: implement "run" backend prototype

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#440]
epic: implement "run" backend prototype

Implement first prototype of the "run" functionality on the backend side.

When a URL like `/run?from=...&name=myworkflow&parameters=myparam;myvalue` is hit, the backend should:

- create workflow with desired name -> this will pre-reserve uuid42
    - internal function; just "pre-register" workflow, since we don't have specs yet
    - this will create also workspace where to fetch sources

- fetch workflow specs
    - if git, then do shallow clone such as `git clone --depth=1` and use `reana.yaml` discovered there
    - if URL to exact `reana.yaml` location, then `wget` it
        - but beware that we won't get input files
    - if Zenodo, then "discover" if `reana.yaml` can be hidden inside tarballs

- fetch workflow parameters
    - if user specifies other input parameters via URL
    - could be perhaps defined in `inputs.yaml` file for Yadage etc

- validate specs on sever-side
    - will require to move some of the workflow validation functions from client-side to server-side

- submit for execution
    - now that everything is specified and "cloned" to workflow, we can launch it

- redirect to /details/uuid42
    - for Web endpoints; for API endpoints return uuid42

This is an epic style issue with musings how the workflow behind the scene could look like.

This issue will generate other issues such as flexible `WorkflowSpecificationFetcher` class, etc. The subsequent issues should stem from this one for better work splitting and progress tracking.

**Comment by VMois** [comment]
Some examples we might target:

- [Zenodo record](https://zenodo.org/record/5752285)
- Github, REANA demo example can be used for a testing
