### ISSUE TITLE
implement flexible workflow specification fetcher

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#441]
When running workflows defined in external sources, there is a need to fetch workflow specification. See parent issue https://github.com/reanahub/reana-server/issues/440

This issue concerns designing and implementing a flexible workflow specification fetcher for a variety of sources:

- if git, then do shallow clone such as `git clone --depth=1` and use `reana.yaml` discovered there
- if URL to exact `reana.yaml` location, then `wget` it
- if Zenodo tarball, then fetch tarball and "discover" `reana.yaml` hidden inside it

We could come up with an abstract `WorkflowSpecificationFetcher` class and subclasses implementing various fetching techniques.

Note that for Serial workflows it may be enough to just deal with `reana.yaml`. But for CWL/Snakemake/Yadage we may need to fetch also `workflow.yaml`, `steps.yaml`, and `inputs.yaml` and friends. (Easy by `git clone`; harder when having only URL since we would have to discover where `steps.yaml` etc are by reading `reana.yaml`.)

The expected outcome of the fetcher is having the files necessary to run the workflow present in a desired output directory. (Which will be equal to workspace location.)

Note: we are not concerned here with how we store the workflow specs in the REANA database etc. The focus is on implementing a flexible component that can run even outside of REANA. We shall plug it into REANA flow as par of the parent issue.

**Comment by mvidalgarcia** [comment]
Side note: We already have some [logic to clone repos](https://github.com/reanahub/reana-workflow-controller/blob/38fdaa25ae089e7297ddc37ee4ce35140aef2028/reana_workflow_controller/rest/utils.py#L317-L319
) in the Workflow-Controller.

Perhaps we should consider encapsulating his logic somewhere to reuse it.
