### ISSUE TITLE
gitlab: verify behaviour when user exceeds quota

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#495]
When a user exceeds disk quota, the CLI way of submitting workflows will prevent user from creating new workflow runs.

The behaviour was verified to work well. However, some improvements were proposed in https://github.com/reanahub/reana-client/issues/607.

This goal of this issue is to do the same verification for GitLab <-> REANA way of submitting workflows:

- will the workflow be prevented from starting?
- will the error message back to GitLab web informative enough?
- will the user sees the core of the issue on the GitLab side?
- will the user know what to do next when this happens?

**Comment by VMois** [comment]
I have triggered and checked how Gitlab will treat our error. It will be silenced and only appear deep in "Webhook" settings. Nothing will appear on a build status page.

We can fix this by applying similar code we have in `r-w-controller/consumer.py` for Gitlab in `r-server` to properly fail build status and pass a detailed description of the error - https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit

**Comment by VMois** [comment]
I have created a draft PR. Code quality is so-so (will be improved before reviewing). Not sure how to test it locally.

**Comment by VMois** [comment]
This issue raises another problem. What will happen if on Gitlab hook workflow fails for other reasons. This is something to discuss in a separate issue, I guess. I can try to fail Gitlab with incorrect `reana.yaml` and see what will happen.
