### ISSUE TITLE
rest: error when uploading empty files

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana-server#498]
How to reproduce:

1. Set disk quota limit
2. Create a new empty file in the directory of a demo example, e.g. `reana-demo-helloworld`
3. Add the file to `inputs.files` in `reana.yaml`
4. Create a new workflow: ` reana-client create -f reana.yaml -w helloworld`
5. Upload the files: `reana-client upload -w helloworld`

reana-client output:
```
==> ERROR: Something went wrong while uploading [...]: 
unsupported operand type(s) for +: 'int' and 'NoneType'
```

reana-server logs:
```
Traceback (most recent call last):
  File "/code/reana_server/rest/workflows.py", line 1211, in upload_file
    prevent_disk_quota_excess(
  File "/code/reana_server/utils.py", line 116, in prevent_disk_quota_excess
    and user_resource.quota_used + bytes_to_sum > user_resource.quota_limit
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by VMois** [comment]
I encountered this bug recently when trying to run the workflow created by our user. The empty `__init__.py` file was defined in `reana.yaml`, and the upload failed.
