### ISSUE TITLE
high REANA_SCHEDULER_REQUEUE_COUNT values lead to deployment troubles

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-server#502]
**Current behaviour**

When a REANA deployment uses low requeue sleep configuration (e.g. 1 sec), they may want to use high requeue count limits so that workflows would not be failed due to inability to get started when the cluster is busy.

Using a high requeue count limit value such as `1000000` leads to helm deployment change for the corresponding environment variable to be:

```diff
            - name: REANA_SCHEDULER_REQUEUE_COUNT
-             value: "200"
+             value: "1e+06"
```

This is problematic, because the environment variable is indeed attempted to be equal to 1e+06, which leads to the deployment crash `CrashLoopBackOff` because the variable is expected to be numerical when the pod is started. 

Note that value of 10000 is OK, which may be enough for many installations... But we should fix the crash for big values.

**Expected behaviour**

We should accept arbitrarily big number that user may want to pass in `REANA_SCHEDULER_REQUEUE_COUNT`.  

Note that `int(1e+06)` would have worked, whilst `int('1e+06')` leads to crash.

**How to test**

```
$ vim helm/configurations/values-dev.yaml
$ git diff
diff --git a/helm/configurations/values-dev.yaml b/helm/configurations/values-dev.yaml
index 94e70de..6d4707d 100644
--- a/helm/configurations/values-dev.yaml
+++ b/helm/configurations/values-dev.yaml
@@ -5,6 +5,7 @@ components:
       image: reanahub/reana-server
       environment:
         REANA_SCHEDULER_REQUEUE_SLEEP: 2
+        REANA_SCHEDULER_REQUEUE_COUNT: 100000
         REANA_RATELIMIT_SLOW: "5 per second"
     reana_workflow_controller:
       image: reanahub/reana-workflow-controller
$ helm diff upgrade reana helm/reana  -f helm/configurations/values-dev.yaml
$ helm upgrade reana helm/reana  -f helm/configurations/values-dev.yaml
```

**Notes**

In addition to fixing the deployment crash for big numbers, we may perhaps want to advertise a special value of `-1` or `0` that would mean "infinity", effectively removing the requeue count functionality.

Also, we may want to check how other variables such as `REANA_SCHEDULER_REQUEUE_SLEEP` behave when passing "unexpected" values.

**Comment by VMois** [comment]
*suggestion:* The easiest way would be to switch `int` to `float` in the `config.py` file for `REANA_SCHEDULER_REQUEUE_COUNT`. It will allow having numbers like `1e+06`. In addition, `float` provides the idea of infinity like this `float("infinity")`. It means that we can allow users to use the value "infinity" for unlimited amounts of re-queue counts.

> Also, we may want to check how other variables such as REANA_SCHEDULER_REQUEUE_SLEEP behave when passing "unexpected" values.

`REANA_SCHEDULER_REQUEUE_SLEEP` uses `float` to interpret string ENV vars. It means it should work with "1e+06", etc. It will fail if the number format is incorrect. But, I don't think we need any validation there unless administrators will ask us to add it.

**Comment by tiborsimko** [comment]
> But, I don't think we need any validation there unless administrators will ask us to add it.

Sure, by "we may want to check" I did not mean to add any validation code for checking; only to look in person at our `values.yaml` for other variables (such as requeue sleep; but not only this one!), try to push some extra huge values there, and check what works and what breaks. The idea was simply to make sure whether we don't need a similar fix for other variables...
