### ISSUE TITLE
admin: add `retention-rules-extend` command

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana-server#556]
Once users define one or more retention rules for one of their workflows, the duration of these rules cannot be modified anymore. 

We should add a new `retention-rules-extend` command that administrators can use to extend the duration of retention rules.

**Comment by tiborsimko** [comment]
The mandatory CLI options would be here (i) the workflow UUID for which we seek the extension, and (ii) the number of  days to extend the rules.   (All homogeneously.)

We could get fancy and accept negative values, which would actually shorten the application waiting times,  which would be another possibility to address some of the "--force-date" use cases for a user. E.g. we extend the retention rules by -10000 days, and then we can simply run the usual daemon without even forcing different date.)
