### ISSUE TITLE
docs: Python supported versions

### ISSUE THREAD

**Issue by Sinclert** [reanahub/reana-server#66]
Given that some of the reana components have different Python versions support (some support 2.7 and 3.6, others only 2.7, and some others only 3.6), Diego and I were thinking about making it more clear by adding ["Python version shields"](https://shields.io) at the top of the `README.md` files.

Example:
![screen shot 2018-07-19 at 15 46 20](https://user-images.githubusercontent.com/6978377/42946343-ea0f5c38-8b6a-11e8-8417-a2baaced2387.png)

In order to do so, I think that the modules need to be uploaded to Pypi. Let us know what you think about this idea.

**Comment by dinosk** [comment]
I think this is a good idea.

**Comment by diegodelemos** [comment]
You can see which packages are already released [here](https://hackmd.web.cern.ch/s/HkLRCDrBQ#Ordered-release-package-list) 🚀

**Comment by Sinclert** [comment]
The shields have been added to all the repositories updated to v0.3.0. 🚀

Closing issue.
