### ISSUE TITLE
tests: add tests for the remaining views

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#97]
Currently only get workflows and create workflow are tested, see [here](https://github.com/reanahub/reana-server/blob/master/tests/test_views.py). Extend tests for the rest of the views.

**Comment by tiborsimko** [comment]
I think this was closed by #98. CC @dinosk

**Comment by dinosk** [comment]
Yes, tests covered that the correct arguments are passed in the calls to RWC and user access, and further testing could be done in integration tests.

**Comment by tiborsimko** [comment]
Let us keep adding `(closes #NNN)` to PR commits so that the closure is automatic :wink:
